version: '3.8'

services:
  gym-backend:
    build:
      context: ./gym-backend/gym-backend-starter
      dockerfile: Dockerfile
    environment:
      - DB-SOURCE=jdbc:postgresql://db:5432/gym_database
      - DB-LOGIN=postgres
      - DB-PASSWORD=mysecretpassword
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - kafka
    ports:
      - "9876:9876"
    networks:
      - gym-network

  gym-mail:
    build:
      context: ./gym-mail-server/gym-mail-starter
      dockerfile: Dockerfile
    environment:
      - DB-SOURCE=jdbc:postgresql://db:5432/gym_database
      - DB-LOGIN=postgres
      - DB-PASSWORD=mysecretpassword
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - kafka
    ports:
      - "5443:5443"
    networks:
      - gym-network

  db:
    image: postgres:13
    container_name: gym-postgres-container
    environment:
      POSTGRES_DB: gym_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - gym-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - gym-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # Ustawienie replication factor na 1
      KAFKA_MIN_INSYNC_REPLICAS: 1        # Ustawienie minimalnej liczby replik
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Ustawienie replication factor dla __consumer_offsets
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gym-network

volumes:
  db-data:

networks:
  gym-network:
    name: my-network-gym-components
