server.port=5443
server.address11=localhost
server.protocol11=http

spring.datasource.url=${DB-SOURCE}
spring.datasource.username=${DB-LOGIN}
spring.datasource.password=${DB-PASSWORD}
spring.profiles.active=${MAIL_PROFILE}
#jpa settings

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=musclemasterytracker@gmail.com
spring.mail.password=bmuwifpwykmgozzy

gym.mail.link.expiration.time.in.minutes=30
gym.mail.registration.subject=muscle mastery tracker registration
gym.mail.advertisement.subject=muscle mastery tracker advertisement
gym.mail.password.reset.subject=muscle mastery tracker advertisement
spring.kafka.bootstrap-servers=kafka:9092
#DB-SOURCE=jdbc:postgresql://localhost:5432/gym_database;DB-LOGIN=postgres;DB-PASSWORD=mysecretpassword
